version: '3'

services:
  # Web server for the ShellRace CTF challenge
  web:
    image: php:8.0-apache
    ports:
      - "80:80"
    volumes:
      - ../:/var/www/html/
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always
    networks:
      - shellrace-network

  # Admin bot that visits the website
  admin-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - web
    environment:
      - NODE_ENV=production
    networks:
      - shellrace-network
    restart: always

networks:
  shellrace-network:
    driver: bridge 